name: CI Pipeline 
on:
  push:
    branches:["master"]
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    -name: Checkout del código 
    uses: actions/checkout@v3
    -name: Configurar Node.js 
    uses: actions/setup-node@v3 
    with: 
    node-version: ‘18'
    -name: Instalar dependencias 
    run: npm install 
    working-directory: ./app
    -name: Ejecutar pruebas 
    run: npm test 
    working-directory: ./app
